// Writes src/source-sans-3.ts and src/noto-sans-sc.ts from the bundled fonts:
// `node packages/core/scripts/font-metrics.mjs`. Rerun it whenever a font in packages/render/fonts changes.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

/** Each bundled face by its style name (ADR-0028), and its file's suffix. */
const FILES = {
  Regular: "Regular",
  Italic: "It",
  Bold: "Bold",
  "Bold Italic": "BoldIt",
  Black: "Black",
  "Black Italic": "BlackIt",
};
/** Noto Sans SC's two faces (ADR-0063). */
const NOTO_FILES = { Regular: "Regular", Bold: "Bold" };

function read(file) {
  const b = readFileSync(new URL(`../../render/fonts/${file}`, import.meta.url));
  const v = new DataView(b.buffer, b.byteOffset, b.byteLength);
  const tables = {};
  for (let i = 0; i < v.getUint16(4); i++) {
    const o = 12 + i * 16;
    tables[b.toString("latin1", o, o + 4)] = v.getUint32(o + 8);
  }
  const { head, hhea, hmtx, cmap, "OS/2": os2 } = tables;
  const numberOfHMetrics = v.getUint16(hhea + 34);
  // Glyphs past numberOfHMetrics repeat the last advance.
  const advance = (glyph) => v.getUint16(hmtx + Math.min(glyph, numberOfHMetrics - 1) * 4);

  // The (3, 10) subtable, format 12: groups of consecutive code points mapped to consecutive glyphs.
  let sub;
  for (let i = 0; i < v.getUint16(cmap + 2); i++) {
    const o = cmap + 4 + i * 8;
    if (v.getUint16(o) === 3 && v.getUint16(o + 2) === 10) sub = cmap + v.getUint32(o + 4);
  }
  if (sub === undefined || v.getUint16(sub) !== 12)
    throw new Error(`${file}: no (3, 10) format 12 cmap.`);
  const advances = {};
  for (let i = 0; i < v.getUint32(sub + 12); i++) {
    const o = sub + 16 + i * 12;
    const [start, end, glyph] = [v.getUint32(o), v.getUint32(o + 4), v.getUint32(o + 8)];
    for (let c = start; c <= end; c++) advances[c] = advance(glyph + c - start);
  }
  // OS/2's typographic ascender and descender, which Inkscape sizes a line by (ADR-0064).
  const vertical = {
    unitsPerEm: v.getUint16(head + 18),
    ascender: v.getInt16(os2 + 68),
    descender: v.getInt16(os2 + 70),
  };
  return { vertical, face: { notdef: advance(0), advances } };
}

const faces = {};
let vertical;
for (const [style, file] of Object.entries(FILES)) {
  const font = read(`SourceSans3-${file}.ttf`);
  // One set of vertical metrics serves every face, so they must agree.
  if (vertical && JSON.stringify(vertical) !== JSON.stringify(font.vertical))
    throw new Error(`${file}: vertical metrics differ from Regular's.`);
  vertical = font.vertical;
  faces[style] = font.face;
}
const out = new URL("../src/source-sans-3.ts", import.meta.url);
writeFileSync(
  out,
  `// Generated by scripts/font-metrics.mjs from the SourceSans3-*.ttf files; do not edit.\n\n` +
    `/** Source Sans 3's bundled faces in font units: the shared typographic ascender and descender, and each face's advance width by code point. */\n` +
    `export const SOURCE_SANS_3 = ${JSON.stringify({ family: "Source Sans 3", ...vertical, faces })} as const;\n`,
);

// Noto Sans SC's advances as runs of consecutive code points sharing one: 30,166 of its 30,890 are
// 1000 wide.
const noto = {};
let notoVertical;
for (const [style, file] of Object.entries(NOTO_FILES)) {
  const { vertical: v, face } = read(`NotoSansSC-${file}.otf`);
  if (v.unitsPerEm !== vertical.unitsPerEm) throw new Error(`${file}: unitsPerEm differs.`);
  if (notoVertical && JSON.stringify(notoVertical) !== JSON.stringify(v))
    throw new Error(`${file}: vertical metrics differ from Regular's.`);
  notoVertical = v;
  const runs = [];
  for (const [c, a] of Object.entries(face.advances).map(([c, a]) => [Number(c), a])) {
    const last = runs.at(-1);
    if (last && last[0] + last[1] === c && last[2] === a) last[1]++;
    else runs.push([c, 1, a]);
  }
  noto[style] = { notdef: face.notdef, runs };
}
const notoOut = new URL("../src/noto-sans-sc.ts", import.meta.url);
writeFileSync(
  notoOut,
  `// Generated by scripts/font-metrics.mjs from the NotoSansSC-*.otf files; do not edit.\n\n` +
    `/** Noto Sans SC's bundled faces in font units: the shared typographic ascender and descender, and each face's advances as sorted runs of [first code point, count, advance]. */\n` +
    `export const NOTO_SANS_SC: { ascender: number; descender: number; faces: Record<"Regular" | "Bold", { notdef: number; runs: [number, number, number][] }> } = ${JSON.stringify({ ascender: notoVertical.ascender, descender: notoVertical.descender, faces: noto })};\n`,
);
execFileSync("pnpm", ["biome", "format", "--write", out.pathname, notoOut.pathname], {
  stdio: "inherit",
});
